final LANG = {
  "ko-KR": {"ko": "한국어", "en": "Korean"},
  "mr-IN": {"ko": "마라티어", "en": "Marathi (India)"},
  "ru-RU": {"ko": "러시아어 (러시아)", "en": "Russian (Russia)"},
  "zh-TW": {"ko": "중국어 (T)", "en": "Chinese (T)"},
  "hu-HU": {"ko": "헝가리어 (헝가리)", "en": "Hungarian (Hungary)"},
  "th-TH": {"ko": "태국어 (태국)", "en": "Thai (Thailand)"},
  "ur-PK": {
    "ko": "우르두어 (파키스탄 이슬람 공화국)",
    "en": "Urdu (Islamic Republic of Pakistan)"
  },
  "nb-NO": {"ko": "노르웨이어", "en": "Norwegian"},
  "da-DK": {"ko": "덴마크어", "en": "Danish (Denmark)"},
  "tr-TR": {"ko": "터키어 (터키)", "en": "Turkish (Turkey)"},
  "et-EE": {"ko": "에스토니아어 (에스토니아)", "en": "Estonian (Estonia)"},
  "bs": {"ko": "보스니아어 (보스니아 헤르체고비나)", "en": "Bosnian (Bosnia and Herzegovina)"},
  "sw": {"ko": "스와힐리어 (케냐)", "en": "Swahili (Kenya)"},
  "pt-PT": {"ko": "포르투갈어 (포르투갈)", "en": "Portuguese (Portugal)"},
  "vi-VN": {"ko": "베트남어", "en": "Vietnamese (Viet Nam)"},
  "en-US": {"ko": "영어 (미국)", "en": "English (United States)"},
  "sv-SE": {"ko": "스웨덴어 (스웨덴)", "en": "Swedish (Sweden)"},
  "ar": {"ko": "아랍어 (UAE)", "en": "Arabic (U.A.E.)"},
  "gu-IN": {"ko": "구자라트어 (인도)", "en": "Gujarati (India)"},
  "kn-IN": {"ko": "칸나다어 (인도)", "en": "Kannada (India)"},
  "el-GR": {"ko": "그리스어 (그리스)", "en": "Greek (Greece)"},
  "hi-IN": {"ko": "힌디어 (인도)", "en": "Hindi (India)"},
  "fi-FI": {"ko": "Finnish (Finland)", "en": "핀란드어 (핀란드)"},
  "fr-FR": {"ko": "프랑스어 (프랑스)", "en": "French (France)"},
  "uk-UA": {"ko": "우크라이나어 (우크라이나)", "en": "Ukrainian (Ukraine)"},
  "en-AU": {"ko": "영어 (호주)", "en": "English (Australia)"},
  "nl-NL": {"ko": "네덜란드어 (네덜란드)", "en": "Dutch (Netherlands)"},
  "fr-CA": {"ko": "프랑스어 (캐나다)", "en": "French (Canada)"},
  "sr": {"ko": "세르비아어", "en": "Serbian"},
  "pt-BR": {"ko": "포르투갈어 (브라질)", "en": "Portuguese (Brazil)"},
  "de-DE": {"ko": "독일", "en": "German"},
  "cs-CZ": {"ko": "체코어 (체코)", "en": "Czech (Czech Republic)"},
  "pl-PL": {"ko": "폴란드어 (폴란드)", "en": "Polish (Poland)"},
  "sk-SK": {"ko": "슬로바키아어 (슬로바키아)", "en": "Slovak (Slovakia)"},
  "it-IT": {"ko": "이탈리아어 (이탈리아)", "en": "Italian (Italy)"},
  "hr": {"ko": "크로아티아어", "en": "Croatian"},
  "zh-CN": {"ko": "중국어", "en": "Chinese (S)"},
  "es-ES": {"ko": "스페인어", "en": "Spanish (Castilian)"},
  "cy": {"ko": "웨일스어 (영국)", "en": "Welsh (United Kingdom)"},
  "ta-IN": {"ko": "타밀어 (인도)", "en": "Tamil (India)"},
  "ja-JP": {"ko": "일본어 (일본)", "en": "Japanese (Japan)"},
  "sq": {"ko": "알바니아어", "en": "Albanian (Albania)"},
  "id-ID": {"ko": "인도네시아어 (인도네시아)", "en": "Indonesian (Indonesia)"},
  "te-IN": {"ko": "텔루구어 (인도)", "en": "Telugu (India)"},
  "ro-RO": {"ko": "루마니아어 (루마니아)", "en": "Romanian (Romania)"},
  "en-GB": {"ko": "영어 (영국)", "en": "English (United Kingdom)"},
  "km-KH": {"ko": "", "en": ""},
  "bn-IN": {"ko": "", "en": ""},
  "fil-PH": {"ko": "fil-PH", "en": "fil-PH"},
  "ml-IN": {"ko": "ml-IN", "en": "ml-IN"},
  "si-LK": {"ko": "si-LK", "en": "si-LK"},
  "ne-NP": {"ko": "ne-NP", "en": "ne-NP"},
  "en-NG": {"ko": "en-NG", "en": "en-NG"},
  "su-ID": {"ko": "su-ID", "en": "su-ID"},
  "bn-BD": {"ko": "bn-BD", "en": "bn-BD"},
  "yue-HK": {"ko": "yue-HK", "en": "yue-HK"},
  "en-IN": {"ko": "en-IN", "en": "en-IN"},
  "es-US": {"ko": "es-US", "en": "es-US"},
  "jv-ID": {"ko": "jv-ID", "en": "jv-ID"},
  "ca": {"ko": "ca", "en": "ca"},
  "ku": {"ko": "ku", "en": "ku"},
  "la": {"ko": "la", "en": "la"},
};
